name: Manual Docker Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Image tag (e.g. v2.0.0)
        default: latest
        required: false
        type: string

jobs:
  deploy:
    permissions:
      contents: read
      packages: write
    uses: bluefunda/release-foundry/.github/workflows/docker-deploy.yml@main
    with:
      tag: ${{ inputs.tag || 'latest' }}
      build-args: VERSION=${{ inputs.tag || 'latest' }}
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
